### PR TITLE
Updated SCSSPHP, Fixed UIKit Compile Bug, Implemented new function for RockFrontend

### PR DESCRIPTION
**Pull request by gs-chofmann**
Hi Bernhard,

I have made a few additions to your plugins.

1) I have updated ScssPHP to the current version 1.12.1

2) I have implemented a fix that solves the UIKit compile error when using ScssPHP and UIKit. The Fix has not yet been implemented in the live version but was confirmed as working here https://github.com/scssphp/scssphp/issues/606 and has also been tested by myself. Since you have bundled ScssPHP with your plugin and its not being auto updated, it should be safe to implement

3) I have created a new function to be used for RockFrontend Module. I will crosslinks my Pull-Request for the RockFrontend Module there, where I have implemented a SCSS Function based on your plugin and code

### CODE REVIEW

**Comment by gs-chofmann** [comment]
Hey @BernhardBaumrock whats the status of this pull request? Whats the status on the SCSS Compiler in Rockfrontend? When will it be integrated in LIVE? Waiting on it for my projects :-)

**Comment by BernhardBaumrock** [comment]
Hey @gs-chofmann sorry I totally missed that one!

I've updated my SCSS module to use automatic versions (see https://processwire.com/talk/topic/28235--) and also updated scssphp to the latest version.

I didn't add the compile method as I didn't want to steal you the credits for being listed as contributor. Could you please create a PR to the DEV branch with only that change?

Or let me know and I'll copy it over. I'll merge the dev branch to main at begin of october!

**Comment by gs-chofmann** [comment]
Hey,

thats fine – go ahead and copy it over 😊
Thank you!

Von: Bernhard Baumrock ***@***.***>
Gesendet: Freitag, 27. September 2024 10:35
An: baumrock/Scss ***@***.***>
Cc: Christian Hofmann ***@***.***>; Mention ***@***.***>
Betreff: Re: [baumrock/Scss] Updated SCSSPHP, Fixed UIKit Compile Bug, Implemented new function for RockFrontend (PR #1)


Hey @gs-chofmann<https://github.com/gs-chofmann> sorry I totally missed that one!

I've updated my SCSS module to use automatic versions (see https://processwire.com/talk/topic/28235--) and also updated scssphp to the latest version.

I didn't add the compile method as I didn't want to steal you the credits for being listed as contributor. Could you please create a PR to the DEV branch with only that change?

Or let me know and I'll copy it over. I'll merge the dev branch to main at begin of october!

**Comment by BernhardBaumrock** [comment]
Here you go, thx! https://github.com/baumrock/Scss/commit/0efb3057c76b0e2a027e7936f9f7bfab4ab49d03

**Pull request closed without merging**
